var searchData=
[
  ['equality_20checks_0',['Equality Checks',['../md_docs_2pages_2Confirmations.html#equality-checks',1,'']]],
  ['erasing_20substrings_1',['Erasing Substrings',['../md_docs_2pages_2StringFunctions.html#erasing-substrings',1,'']]],
  ['example_2',['Example',['../structstd_1_1formatter_3_01T_01_4.html#example',1,'Example'],['../macros_8h.html#example-1',1,'Example'],['../macros_8h.html#example-2',1,'Example'],['../macros_8h.html#example-3',1,'Example'],['../namespaceutilities.html#example-4',1,'Example'],['../namespaceutilities.html#example-5',1,'Example'],['../namespaceutilities.html#example-6',1,'Example'],['../namespaceutilities.html#example-7',1,'Example'],['../namespaceutilities.html#example-8',1,'Example'],['../namespaceutilities.html#example-9',1,'Example'],['../namespaceutilities.html#example-10',1,'Example'],['../namespaceutilities.html#example-11',1,'Example'],['../namespaceutilities.html#example-12',1,'Example'],['../namespaceutilities.html#example-13',1,'Example'],['../namespaceutilities.html#example-14',1,'Example'],['../namespaceutilities.html#example-15',1,'Example'],['../namespaceutilities.html#example-16',1,'Example'],['../namespaceutilities.html#example-17',1,'Example'],['../namespaceutilities.html#example-18',1,'Example'],['../namespaceutilities.html#example-19',1,'Example'],['../namespaceutilities.html#example-20',1,'Example'],['../namespaceutilities.html#example-21',1,'Example'],['../namespaceutilities.html#example-22',1,'Example'],['../namespaceutilities.html#example-23',1,'Example'],['../namespaceutilities.html#example-24',1,'Example'],['../namespaceutilities.html#example-25',1,'Example'],['../namespaceutilities.html#example-26',1,'Example'],['../namespaceutilities.html#example-27',1,'Example'],['../namespaceutilities.html#example-28',1,'Example'],['../namespaceutilities.html#example-29',1,'Example'],['../namespaceutilities.html#example-30',1,'Example'],['../namespaceutilities.html#example-31',1,'Example'],['../namespaceutilities.html#example-32',1,'Example'],['../namespaceutilities.html#example-33',1,'Example'],['../namespaceutilities.html#example-34',1,'Example'],['../namespaceutilities.html#example-35',1,'Example'],['../namespaceutilities.html#example-36',1,'Example'],['../namespaceutilities.html#example-37',1,'Example'],['../namespaceutilities.html#example-38',1,'Example'],['../namespaceutilities.html#example-39',1,'Example'],['../namespaceutilities.html#example-40',1,'Example'],['../namespaceutilities.html#example-41',1,'Example'],['../md_docs_2pages_2Confirmations.html#example-42',1,'Example'],['../md_docs_2pages_2Formatter.html#example-43',1,'Example'],['../md_docs_2pages_2Logging.html#example-44',1,'Example'],['../md_docs_2pages_2Logging.html#example-45',1,'Example'],['../md_docs_2pages_2Macros.html#example-46',1,'Example'],['../md_docs_2pages_2Macros.html#example-47',1,'Example'],['../md_docs_2pages_2Stopwatch.html#example-48',1,'Example'],['../md_docs_2pages_2StringFunctions.html#example-49',1,'Example'],['../md_docs_2pages_2PrettyPrinting.html#example-50',1,'Example'],['../md_docs_2pages_2TypeStrings.html#example-51',1,'Example']]],
  ['execute_3',['Print Code &amp;amp; Execute',['../md_docs_2pages_2Macros.html#print-code--execute',1,'']]],
  ['expansion_4',['Macro Expansion',['../md_docs_2pages_2Macros.html#macro-expansion',1,'']]],
  ['extracting_20values_5',['Extracting Values',['../md_docs_2pages_2StringFunctions.html#extracting-values',1,'']]]
];
