/// @brief Exercise std::format a little.
/// @copyright Copyright (c) 2024 Nessan Fitzmaurice
#include "utilities/format.h"
#include "utilities/macros.h"
#include <iostream>
#include <string>

int
main()
{
    // clang-format off
    auto s = std::format(
                "A "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "really really really really really really really really really "
                "long string");

    // clang-format on
    std::cout << "String s:\n"
              << s << "\n"
              << "The string has length: " << s.length() << '\n';

    return 0;
}