/// Exercise std::format a little.

#include "utilities/formatter.h"
#include <print>

int
main()
{
    // clang-format off
    std::println(
        "A "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "really really really really really really really really really "
        "long string");
    // clang-format on

    return 0;
}