// This file was generated by running the script `doxytest.py` to extract tests from comments in input files.
// Input file(s): `type.h`
// Do not edit this file manually -- it may be overwritten.
// Generated on: 2025-10-29 15:40:12

#include "../include/utilities/type.h"
#include <print>

int main() {
    std::println(stderr, "No test cases were found in `type.h`.");
}