// This file was generated by running the script `doxytest.py` to extract tests from comments in input files.
// Input file(s): `stopwatch.h`
// Do not edit this file manually -- it may be overwritten.
// Generated on: 2025-10-30 12:53:15

#include "../include/utilities/stopwatch.h"
#include <print>

int main() {
    std::println(stderr, "No test cases were found in `stopwatch.h`.");
}