// This file was generated by running the script `doxytest.py` to extract tests from comments in input files.
// Input file(s): `assert.h`
// Do not edit this file manually -- it may be overwritten.
// Generated on: 2025-10-30 17:08:18

#include "../include/utilities/assert.h"
#include <print>

int main() {
    std::println(stderr, "No test cases were found in `assert.h`.");
}