# Metadata for this documentation project.
# See https://quarto.orgpages/reference/projects/websites.html
project:
  type: website
  output-dir: _site

# Extensions:
# simple-vars: Lets us reference variables as `{name}`  instead of the wordier `{{< var name >}}`
# admonitions: A simpler alternative to Quarto callout blocks.
filters:
  - simple-vars
  - admonitions

format:
  html:
    toc: true
    toc-expand: true
    code-copy: true
    code-overflow: scroll
    grid:
      sidebar-width: 250px
      body-width: 950px
      margin-width: 200px
      gutter-width: 1.5em
    theme:
      light:
        - cosmo
        - assets/css/theme.scss
        - assets/css/extras.scss
      dark:
        - cosmo
        - assets/css/theme.scss
        - assets/css/dark.scss
        - assets/css/extras.scss

website:
  title: "C++ Utilities Library"
  image: "assets/images/logo.png"
  favicon: "assets/images/logo.png"
  open-graph: true
  google-analytics: G-XHMT1TRH0L
  site-url: "https://nessan.github.io/utilities"
  repo-url: "https://github.com/nessan/utilities"
  repo-subdir: docs
  issue-url: "https://github.com/nessan/utilities/issues/new/choose"
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: false
  back-to-top-navigation: true
  page-footer:
    left: |
      &#169; 2022 Nessan &#8729; Made with [Quarto](https://quarto.org)
    center:
      - icon: github
        href: "https://github.com/nessan/utilities"
        aria-label: GitHub Repo
      - icon: envelope
        href: "mailto:nzznfitz+gh@icloud.com"
        aria-label: EMail address
    right: |
      [MIT Licensed](https://opensource.org/license/mit)

  navbar:
    background: dark
    logo: "assets/images/logo.png"
    logo-alt: "The utilities library logo"
    title: utilities
    search: true
    pinned: true
    collapse-below: lg
    left:
      - text: "Home"
        file: pages/index.qmd
      - text: "Assertions"
        file: pages/assert.qmd
      - text: "Logging"
        file: pages/log.qmd
      - text: "Stopwatch"
        file: pages/stopwatch.qmd
      - text: "Strings"
        file: pages/string.qmd
      - text: "Streams"
        file: pages/stream.qmd
      - text: "Commas"
        file: pages/thousands.qmd
      - text: "Macros"
        file: pages/macros.qmd
      - text: "Types"
        file: pages/type.qmd
      - text: "Format"
        file: pages/format.qmd
      - text: "More"
        menu:
          - text: "Project Repo"
            icon: "github"
            href: "https://github.com/nessan/utilities"
          - text: "Report a Bug"
            icon: "bug"
            href: "https://github.com/nessan/utilities/issues"
          - text: "Ask a Question"
            icon: "chat-right-text"
            href: "mailto:nzznfitz+gh@icloud.com"
    tools:
      - icon: github
        href: "https://github.com/nessan/utilities"
        text: GitHub repo

  sidebar:
    style: floating
    type: light
    background: light
    align: left
    collapse-level: 2
    contents:
      - text: "Library Overview"
        file: pages/index.qmd
      - text: "Assertions"
        file: pages/assert.qmd
      - text: "Logging"
        file: pages/log.qmd
      - text: "Stopwatch"
        file: pages/stopwatch.qmd
      - text: "String Functions"
        file: pages/string.qmd
      - text: "Stream Functions"
        file: pages/stream.qmd
      - text: "Readable Numbers"
        file: pages/thousands.qmd
      - text: "Useful Macros"
        file: pages/macros.qmd
      - text: "Type Names"
        file: pages/type.qmd
      - text: "Formatted Output"
        file: pages/format.qmd
editor:
  markdown:
    canonical: true
