# Triggers a fresh build of the projects's documentation site.
# The source for the site is in the docs/ subdirectory.
# We publish the site to github pages.
# The site is built using the Quarto static generator (see https://quarto.org).
name: Quarto Publish

# When is the workflow run?
on:
    # Any push to the main branch that changes the site content.
    push:
        branches:
            - main
        paths:
            - "docs/**"
    # Any formal release
    release:
        types: [published]

    # You can also trigger the workflow manually (handy to debug the workflow).
    workflow_dispatch:

# Just the one job in the workflow.
jobs:
    quarto-publish:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Set up Quarto
              uses: quarto-dev/quarto-actions/setup@v2

            - name: Publish the site to gh-pages
              uses: quarto-dev/quarto-actions/publish@v2
              with:
                  target: gh-pages
                  path: docs
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
